Empresa/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('puzzle/',include('puzzle.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls'))
    
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puzzle/urls.py

from django.urls import path,include 

from puzzle.views import(   
        
        index,
        puzzle_game,
        growing_mode,
        family_mode,
        #zooListView
        #PhotoView
        pickAnimal,
        animalGrow,
        animal,        
        score,     
        signup
        )

app_name = 'puzzle'
urlpatterns = [
    path('', index, name='index'),
    
    #url(r'^addresses/$',addresses),
    #url(r'^photos/$',photos),
    #path('<int:id>/',PhotoView.as_view(template_name='puzzle/photo.html'),name='photo-detail'),
	path('puzzle_game/<int:specieId>/', puzzle_game, name='puzzle_game'),    
	path('animalGrow/',animalGrow, name='animalGrow'),
	path('family_mode/', family_mode, name='family_mode'),
   path('pickAnimal/',pickAnimal,name='pickAnimal'),
   path('animal/<int:specieId>/',animal,name='animal'),
   
   path('score/',score,name='score'),
   path('signup/', signup, name='signup'),
    
   # path('',zooListView.as_view(),name='zoo-list')
   #path('photos',PhotoView.as_view(template_name='puzzle/photo.html'),name='photo-list')
        
    #path('puzzle_game/', puzzle_game, name='puzzle_game'),
   
]




urls.py

from django.urls import path,include 

from puzzle.views import(   
        
        index,
        puzzle_game,       
        family_mode,
        #zooListView
        #PhotoView
        pickAnimal,
        animalGrow,
        animal,        
        score,     
        signup,
        modes,
        info,
        header,
        )

app_name = 'puzzle'
urlpatterns = [
    path('', index, name='index'),   
	path('puzzle_game/<int:specieId>/', puzzle_game, name='puzzle_game'),    
	path('animalGrow/',animalGrow, name='animalGrow'),
	path('family_mode/', family_mode, name='family_mode'),
   path('pickAnimal/',pickAnimal,name='pickAnimal'),
   path('animal/<int:specieId>/',animal,name='animal'),   
   path('score/',score,name='score'),
   path('signup/', signup, name='signup'),    
   path('modes/',modes,name='modes'),
   path('info/',info,name='info'),
    path('header/',header,name='header'),
   
        
 
   
]




puzzle/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
# Create your models here.

class level(models.Model):
    level_id = models.IntegerField(primary_key=True)
    level_desc = models.CharField(max_length=10)
    level_score = models.IntegerField()
    def __str__(self):
        result = str(self.level_id) + '\n' + self.level_desc + '\n' + str(self.level_score)
        return result
    
class Address(models.Model):
    address= models.IntegerField(db_index=True)
    city = models.CharField(max_length=20,null=True)
    suburb = models.CharField(max_length=20,null=True)
    postcode = models.CharField(max_length=4,null=True)
    street = models.CharField(max_length=50,null=True)    
    def __str__(self):
        result = str(self.address) + '\n' + self.city + '\n' + self.suburb + '\n' + str(self.postcode) + '\n' + self.street
        return result

class User(AbstractUser):    
    user_id = models.IntegerField(primary_key=True,db_index=True)
    username =models.CharField(max_length=15,null=True,unique=True)  
    password = models.CharField(max_length=15,null=True,unique=True)
    postcode = models.CharField(max_length=4,null=True)      
    user_score = models.IntegerField(default=100)
    
    USERNAME_FIELD = 'username'
    PASSWORD_FIELD = 'password'
    class Meta(AbstractUser.Meta):
        pass
    
class Zoo(models.Model):
    zoo_id = models.IntegerField(primary_key=True,db_index=True)    
    zoo_logo = models.ImageField(upload_to='puzzle',blank=True,null=True)
    zoo_name = models.CharField(max_length=200,null=True)
    zoo_city = models.CharField(max_length=20,null=True)
    zoo_suburb = models.CharField(max_length=20,null=True)
    zoo_post = models.IntegerField()
    zoo_street = models.CharField(max_length=50,null=True)
    zoo_open = models.DateTimeField('zoo open time')
    zoo_close = models.DateTimeField('zoo close time')
    def __str__(self):
        return self.zoo_name


    
class Specie(models.Model):    
    specie_id = models.IntegerField(primary_key=True,db_index=True)
    specie_name = models.CharField(max_length=300,null=True,blank=True)
    specie_desc = models.CharField(max_length=300,null=True,blank=True,default='')
    easy = models.CharField(max_length=1000,null=True,blank=True,default='')
    medium = models.ImageField(upload_to='puzzle/',blank=True,null=True)
    diff = models.CharField(max_length=1000,null=True,blank=True,default='')
    def __str__(self):
        return str(self.specie_id) 
    
class Photo(models.Model):
    photo_id = models.IntegerField(primary_key=True,db_index=True)
    photo_desc = models.CharField(max_length=300,null=True)    
    image = models.ImageField(upload_to='puzzle/',blank=True,null=True)
    specie = models.ForeignKey(Specie,on_delete=models.CASCADE,blank=True,null=True)
    def __str__(self):
        return self.photo_desc
    def get_absolute_url(self):
        #return reverse("photos",kwargs={"id":self.photo_id})#f"/photos/{self.photo_id}/"
        return "/photos/{self.photo_id}"
    
class Food(models.Model):
    foodName = models.CharField(max_length=20,null=True)
    food_img = models.ImageField(upload_to='puzzle/',blank=True,null=True)
    food_score =models.IntegerField(default=10)
    specie = models.ForeignKey(Specie,on_delete=models.CASCADE,blank=True,null=True)

class Puzzle(models.Model):
    puzzle_id = models.IntegerField(primary_key=True,db_index=True)
    picture = models.ForeignKey(Photo,on_delete=models.CASCADE)
    level = models.ForeignKey(level,on_delete=models.CASCADE)
    specie = models.ForeignKey(Specie,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    startTime = models.DateTimeField('time start play')
    endTime = models.DateTimeField('time finish play')
    
class Tool(models.Model):
    toolName = models.CharField(max_length=20,null=True)
    tool_img = models.ImageField(upload_to='puzzle/',blank=True,null=True)
    tool_score = models.IntegerField(default=20)

puzzle/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render,redirect
from django.views import generic, View
from .models import Address,Photo,Zoo,Specie,Puzzle,User,Food
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.core import serializers
import json
from django.template import RequestContext, loader
from django.views.decorators.csrf import csrf_protect
from django.db.models import Q
from django.contrib.auth import logout,login,authenticate
from puzzle.forms import SignUpForm

def photos(request):
    photoList = Photo.objects.all()
    return render(request,'puzzle/photo.html',{"photos":photoList})
	
def index(request):
    address_list = Address.objects.all()
    context = {'address_list': address_list,}
    return render(request, 'puzzle/index.html', context)

def puzzle_game(request,specieId):
    # = where specie=specieid and photo_desc like 'puzzle%'
    photoList = Photo.objects.filter(Q(specie=specieId),Q(photo_desc__startswith='puzzle'))
    # pass specie description
    specie = Specie.objects.get(pk=specieId)
    context = {
            "imageList" : photoList,
            "specie_desc" : specie.specie_desc,
            "easy":specie.easy,
            "medium":specie.medium,
            "diff":specie.diff,
            "specie_id":specieId
            }           
    
    return render(request,'puzzle/puzzle.html',context)  
	
def growing_mode(request):
    return render(request, 'puzzle/grow.html')

def family_mode(request):
    zooList = Zoo.objects.all()
    return render(request,'puzzle/family.html',{
            'zooList':zooList           
            })    
    #display puzzle photo

def pickAnimal(request):
    specieList = Specie.objects.all()
    imageList = Photo.objects.all()    
    
    context = {
            "specieList" : specieList ,
            "imageList": imageList
            }
    return render(request,'puzzle/pickAnimal.html',context) 
    

def animalGrow(request):
    unlock = True
    context ={
            "unlock": unlock,
            }
    return render(request, 'puzzle/animalForGrow.html',context)

def animal(request,specieId):
    template = 'puzzle/animal1.html'
    foodlist = Food.objects.values('food_img')
    specie = Specie.objects.get(pk=specieId)
    img = Photo.objects.filter(Q(specie=specieId),Q(photo_desc__startswith='grow'))
    context = {
            "specieId":specieId,
            "specie":specie,
             "specieimg" : img,
             "food" : foodlist             
            }
    return render(request,template,context)

@csrf_protect
def score(request):
    from django.http import JsonResponse
    if request.method =='POST' and request.is_ajax():
        try:
            username = request.POST['username']
            user = User.objects.get(username=username)
            user.user_score = request.POST['score']
            user.save()
            return JsonResponse({'status':'Success', 'msg': 'save successfully'})
        except User.DoesNotExist:
            return JsonResponse({'status':'Fail', 'msg': 'Object does not exist'})
    else:
         return JsonResponse({'status':'Fail', 'msg':'Not a valid request'})
def signup(request):
    form=SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            postcode = form.cleaned_data.get('postcode')
            user = authenticate(username=username, password=raw_password,postcode=postcode)
            
            
    else:
        print(form.errors)
    return render(request, 'registration/signup.html', {'register_form': form})


    

puzzle/templates/puzzle/animal2.html
<script src="https://cdn.bootcss.com/jquery/1.11.0/jquery.min.js"></script>
<script src="http://code.changer.hk/jquery/plugins/jquery.cookie.js"></script>



{% include 'puzzle/footer.html' %}

<div id ="result">
</div>
<script type = "text/javascript">
var name = sessionStorage.getItem("name");
var a =$.cookie('simple');

document.getElementById("result").innerHTML = a;



var url = "{% url "puzzle:score" %}"



$.ajax({
    url:url,
    type:"POST",
    data:{'csrfmiddlewaretoken' : "{{  csrf_token  }}",'username':'{{request.user.username}}',"score":70},
    success: function(result){}
});

</script>

puzzle/templates/puzzle/animal4.html
{% include 'puzzle/navbar.html' %}

{% include 'puzzle/footer.html' %}

puzzle/templates/puzzle/animal5.html
{% include 'puzzle/navbar.html' %}

{% include 'puzzle/footer.html' %}

puzzle/templates/puzzle/animalForGrow.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Grow Mode</title> 
        <link href="{% static "css/animalForGrow.css" %}" rel="stylesheet" type="text/css"/>
        <script src="https://cdn.bootcss.com/jquery/1.11.0/jquery.min.js"></script>        
        <script src="{% static "js/jquery.cookie.js" %}"></script>
        <script type="text/javascript" src="{% static "js/jquery.SuperSlide.2.1.1.js" %}"></script>
    </head>
    <body>
    {% include 'puzzle/navbar.html' %}
        <div class="home-banner">
            <div class="home-banner-box">
                <div class="home-banner-head">
                    <h2 id="title">Select the animal to start</h2>
                </div>
            </div>
            <div class="home-banner-body">
                <div class="home-banner-bg"></div>
                <div class="home-banner-slider">
                    <div class="home-banner-con">
                        <div class="home-shadow">
                            <div class="home-banner-line">
                                <div class="home-banner-list">
                                    <div class="item-q"></div>
                                    <div class="item-q"></div>
                                    <div class="item-q"></div>
                                </div>
                            </div>
                            <div class="bd">
                                <ul>
                                    <li>
                                        <img  src="{% static "images/animal1.jpg" %}" alt="">
                                        <div class="home-banner-text">
                                            <div class="home-title">Black-eared Miner</div>
                                            <div class="home-text">The black-eared miner (Manorina melanotis) is an endangered honeyeater endemic to mallee woodland in south-eastern Australia.</div>
                                            <div class="home-button">
                                                <a id ="1" href="{% url 'puzzle:animal' 1  %}">Start</a>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                      
                                        <img src="{% static "images/animal2.jpg" %}" alt="">
                                        <div class="home-banner-text">
											<div class="home-title">Mountain Pygmy Possum </div>
                                            <div class="home-text"> Climate change is a major threat to the possum because as their habitat changes, hibernation patterns alter and food sources become scarcer.</div>
                                            <div class="home-button"><a id="2" href="{% url 'puzzle:animal' 2  %}">Start</a></div>
                                        </div>
                                    </li>
                                    <li>
                                       
                                        <img  src="{% static "images/animal3.jpg" %}" alt="">
                                        <div class="home-banner-text">
											<div class="home-title">Lesser Sand Plover</div>
                                            <div class="home-text">The Lesser Sand Plover is often gregarious during the non-breeding season, when it occurs in small parties or larger flocks of up to several hundred birds, though it sometimes feeds singly</div>
                                            <div class="home-button"><a id="3" href="{% url 'puzzle:animal' 3  %}">Start</a></div>
                                        </div>
                                    </li>
        								  <li>
            			
                                        <img  src="{% static "images/animal4.jpg" %}" alt="">
                                        <div class="home-banner-text">
											<div class="home-title">Chatham Albatross</div>
                                            <div class="home-text">They are normally silent, but will emit a harsh buzzing bray when threatened and also during courtship.</div>
                                            <div class="home-button"><a id="4" href="{% url 'puzzle:animal' 4  %}">Start</a></div>
                                        </div>
                                    </li>
    									  <li>
        								
                                        <img  src="{% static "images/animal5.jpg" %}" alt="">
                                        <div class="home-banner-text">
											<div class="home-title">Long-footed Potoroo</div>
                                            <div class="home-text">The long-footed potoroo lives in a range of montane forests. It has also been found in the warmer temperate rainforest. This species lives where the soil is constantly moist.</div>
                                            <div class="home-button"><a id="5" href="{% url 'puzzle:animal' 5  %}">Start</a></div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <a href="javascript:void(0)" class="prev"></a>
                    <a href="javascript:void(0)" class="next"></a>
                </div>
            </div>
        </div>
 {% include 'puzzle/footer.html' %}      
<script type ="text/javascript">
var startlock = document.getElementsByClassName("home-button");
exist = new Array();
exist[0] = -1;
for (i=1;i<6;i++){
    key = eval("'"+i+"'");
    //document.write($.cookie(key))
    if ($.cookie(key) == undefined ) {
        var element = document.getElementById(key);
        element.style.display = "none";
        startlock[i-1].insertAdjacentHTML('afterbegin','<img class="lock-btn" src="{% static "images/btn3.png" %}">');
     }
}

 // alert when user click lock btn
  var lockbtn = document.getElementsByClassName("lock-btn")
  for (i=0;i<lockbtn.length;i++) {
      lockbtn[i].addEventListener("click", function() {
      alert("You need to complete the puzzles first")
  });
  }

</script> 

<script type="text/javascript">
    jQuery(".home-banner-slider").slide({
        mainCell: ".bd ul",
        effect: "left",
        autoPlay: false,
        delayTime: 700
    });
</script>
		

    </body>
</html>;

puzzle/templates/puzzle/modeSelection.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Game center</title>
<meta name="author" content="Themezinho">
<meta name="description" content="Anchor | Freelancer & Creative Agency Portfolio">
<meta name="keywords" content="creative, works, showcase, portfolio, highlight, projects, parallax, agency, digital, studio, css, animation, transition, svg, html, css">
<!-- FAVICON FILES -->
<link href="ico/apple-touch-icon-144-precomposed.png" rel="apple-touch-icon" sizes="144x144">
<link href="ico/apple-touch-icon-114-precomposed.png" rel="apple-touch-icon" sizes="114x114">
<link href="ico/apple-touch-icon-72-precomposed.png" rel="apple-touch-icon" sizes="72x72">
<link href="ico/apple-touch-icon-57-precomposed.png" rel="apple-touch-icon">
<link href="ico/favicon.png" rel="shortcut icon">

<!-- CSS FILES -->
<link rel="stylesheet" href="{% static "css/new/bootstrap.min.css" %}">
<link rel="stylesheet" href="{% static "css/new/style.css" %}">
<link rel="stylesheet" href="{% static "css/new/animate.min.css" %}">
<link rel="stylesheet" href="{% static "css/new/hamburger-menu.css" %}">
<link rel="stylesheet" href="{% static "css/new/odometer.min.css" %}">
<link rel="stylesheet" href="{% static "css/new/swiper.min.css" %}">
<link rel="stylesheet" href="{% static "css/new/fancybox.min.css" %}">
  
</head>
<body>
<div class="preloader"> <img src="{% static "images/new/preloader.gif" %}" alt="Image">
  <ul class="text-rotater">
    <li>Hangin there</li>
    <li>Still loading</li>
    <li>Almost done</li>
  </ul>
</div>
<div class="transition-overlay"></div> 
<main>
	<ul class="hamburger-navigation">
		<li><a href="{% url 'puzzle:index' %}">Go Home</a> </li>
		<li><a href="#">Game Center</a> </li>
		<li><a href="{% url 'puzzle:info' %}">Information Page</a> </li>
		{% if request.user.is_authenticated %}
		<li><a>Hi,{{request.user.username}}</a></li>
		<li><a>Your Score: {{request.user.user_score}}</a></li>
		<li><a href="{% url 'logout'%}">logout</a></li>
		{% else %}
		<a href="{% url 'login' %}"><strong>login</strong></a>
		{% endif %}
	</ul>
   <svg class="shape-overlays" viewBox="0 0 100 100" preserveAspectRatio="none">
    <path class="shape-overlays__path" d=""></path>
    <path class="shape-overlays__path" d=""></path>
    <path class="shape-overlays__path" d=""></path>
  </svg>
  <header class="header">
    <!--div class="logo"><img src="{% static "images/new/logo.png" %}" alt="Image"></!--div>-->
    <!-- end logo -->     
    <div class="hamburger" id="hamburger">
      <div class="hamburger__line hamburger__line--01">
        <div class="hamburger__line-in hamburger__line-in--01"></div>
      </div>
      <div class="hamburger__line hamburger__line--02">
        <div class="hamburger__line-in hamburger__line-in--02"></div>
      </div>
      <div class="hamburger__line hamburger__line--03">
        <div class="hamburger__line-in hamburger__line-in--03"></div>
      </div>
      <div class="hamburger__line hamburger__line--cross01">
        <div class="hamburger__line-in hamburger__line-in--cross01"></div>
      </div>
      <div class="hamburger__line hamburger__line--cross02">
        <div class="hamburger__line-in hamburger__line-in--cross02"></div>
      </div>
    </div>
    <!-- end hamburger -->
    <div class="equalizer"> <span></span> <span></span> <span></span> <span></span> </div>
    <!-- end equalizer -->
    
  </header> 
  <section class="int-hero">
    {% include 'puzzle/dog.html'%}    
   
    <!--div id="barchart"></div-->    
    <div class="inner">
    <h2>Come on ! Follow me to meet your new friends!<h2>
    <p class="text-right">    
    </div>    
 </section>

{% include 'puzzle/test1.html' %}

<!-- end footer-spacing -->
{% include 'puzzle/footer.html' %}
</main>
<!--div class="footer-spacing"></div-->

<!-- end footer -->
<audio id="link" src="{% static "audio/link.mp3" %}"preload="auto"></audio>

<!-- JS FILES --> 
<script src="{% static "js/new/jquery.min.js" %}"></script> 
<script>
	
		(function($) {
			$(window).load(function(){
				$("body").addClass("page-loaded");	
			});
		})(jQuery)
		
		
anychart.onDocumentReady(function () {
	
// create data
var data = [['Black-eared miner', 390], ['Mountain Pygmy-possum', 2250],['Lesser Sand Plover', 3327],['Chatham Albatross',11000],['Long-footed Potoroo',1500],];

// create a chart
chart = anychart.bar();

// create a bar series and set the data
var series1 = chart.bar(data);
// configure the visual settings of the first series
series1.normal().fill("#00cc99", 0.3);
series1.hovered().fill("#00cc99", 0.1);
series1.selected().fill("#00cc99", 0.5);
series1.normal().stroke("#00cc99", 1, "10 5", "round");
series1.hovered().stroke("#00cc99", 2, "10 5", "round");
series1.selected().stroke("#00cc99", 4, "10 5", "round");
series1.labels(true);
series1.labels().format("{%value} Alive subject");
// set the container id
chart.container("barchart");

// initiate drawing the chart
chart.draw();
	
	
});
</script> 
<script src="{% static "js/new/bootstrap.min.js" %}"></script> 
<script src="{% static "js/new/swiper.min.js" %}"></script> 
<script src="{% static "js/new/fancybox.min.js" %}"></script> 
<script src="{% static "js/new/jquery.stellar.js" %}"></script> 
<script src="{% static "js/new/odometer.min.js" %}"></script> 
<script src="{% static "js/new/hamburger.min.js" %}"></script> 
<script src="{% static "js/new/easings.js" %}"></script> 
<script src="{% static "js/new/isotope.min.js" %}"></script> 
<script src="{% static "js/new/wow.min.js"></script> 
<script src="{% static "js/new/perspective.min.js" %}"></script> 
<script src="{% static "js/new/scripts.js" %}"></script>
</body>
</html>

puzzle/templates/puzzle/navbar.html
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.dropbtn {
  
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
}

.dropdown {
  position: absolute;
  display: inline-block;
  margin-right:10px;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.loginbtn{
    color: black;
    padding: 12px 16px;
 
}


.dropdown-content a:hover {background-color: #ddd;}

.dropdown:hover .dropdown-content {display: block;}

.dropdown:hover .dropbtn {background-color: #3e8e41;}
</style>

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0px; background-color: #84EBA6;">
  <!-- Brand and toggle get grouped for better mobile display -->
	<div class="container-fluid" style="float:left">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'puzzle:index' %}" style="color:#fff">Home Page</a>
			<a class="navbar-brand" href="{% url 'puzzle:info' %}">Information Page</a>
			<a class="navbar-brand" href="{% url 'puzzle:modes' %}">Game Center</a>
		</div>
		
		<!-- Collect the nav links, forms, and other content for toggling -->

		<div class="dropdown">
			{% if request.user.is_authenticated %}
			<button class="dropbtn" data-toggle="dropdown">{{ request.user.username }}</button>
			<div class="dropdown-content">
				<a href="#nowhere">My Score:{{ request.user.user_score }}</a>
				<a href="{% url 'logout'%}">logout</a>
			</div>
			{% else %}
			<div class="loginbtn">
				<p>You are not logged in</p><a href="{% url 'login' %}"><strong>login</strong></a>
			</div>
			{% endif %}
		</div>




</nav>